/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.OperarioControll;
import Model.Funcionario;
import TableModel.OperarioTM;
import Util.ValidaData;

import javax.swing.JOptionPane;

/**
 * A classe TCadastroOperario estende as características de javax.swing.JFrame, portanto ela é uma classe de interface
 * gráfica com interação com o usuario e é responsável por receber os dados que vão ser atríbutos a cada novo Operario
 * criado, editar ou excluir operarios já instanciados.
 * @author Pedro Henrique 
 * @version 3.0 (nov. 2020)
 */
public class TCadastroOperario extends javax.swing.JFrame { 
	//atributos
    private String data;
    private ValidaData hoje= new ValidaData("01/01/1994",ValidaData.BarraSemHora);
    private OperarioTM Modelo3;
    public static int index;
    public static int flag;
   
    /**
     * O metodo LoadTableOperario é responsável por atualizar os novos valores fornecidos a cada nova mudança 
     * na tabela de operarios.
     * 
     */
    public void LoadTableOperario(){
         Modelo3= new OperarioTM(OperarioControll.getOperarios());
         jTableOperario.setModel(Modelo3);   
     }
    /**
     * O metodo Botoes é responsável por ditar a visibilidade de todos os botões presentes na classe.
     * @param N Botao Novo
     * @param E Botao Editar
     * @param R Botao Excluir
     * @param S Botao Salvar
     * @param C Botao cancelar
     */
     public void Botoes(boolean N, boolean E, boolean R, boolean S, boolean C){
        jButtonNovoO.setEnabled(N);
        jButtonEditarO.setEnabled(E);
        jButtonExcluirO.setEnabled(R);
        jButtonSalvarO.setEnabled(S);
        jButtonCancelarO.setEnabled(C);        
    }
     /**
      * O metodo construtor da classe é responsável por carregar todos os componentes necessários logo após a interface
      * ser chamada.
      * 
      */ 
    public TCadastroOperario() {
        initComponents();
       // txtNumFunc.setText(Integer.toString(Funcionario.quantidadeFuncionarios()));
        setLocationRelativeTo(null);
        LoadTableOperario();
        Botoes(true,false,false,false,false);
        jTextFieldCodigo.setEnabled(false);    
        jTextFieldNome.setEnabled(false);
        jTextFieldFiliacao.setEnabled(false);
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldComissao.setEnabled(false);
        jTextFieldCargo.setEnabled(false);
        jTextFieldTelefone.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldDepartamento.setEnabled(false);
        jTextFieldSalario.setEnabled(false);
        jTextFieldSexo.setEnabled(false);
        jTextFieldDataNasc.setEnabled(false);
        jTextFieldHabilidades.setEnabled(false);
        jTextFieldTiposTrab.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldFiliacao = new javax.swing.JTextField();
        jTextFieldCargaHoraria = new javax.swing.JTextField();
        jTextFieldComissao = new javax.swing.JTextField();
        jTextFieldCargo = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jTextFieldSalario = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jTextFieldHabilidades = new javax.swing.JTextField();
        jTextFieldTiposTrab = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelFiliacao = new javax.swing.JLabel();
        jLabelCargaHoraria = new javax.swing.JLabel();
        jLabelComissao = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelIcone = new javax.swing.JLabel();
        jLabelHabilidades = new javax.swing.JLabel();
        jLabelTiposTrab = new javax.swing.JLabel();
        jButtonSalvarO = new javax.swing.JButton();
        jButtonCancelarO = new javax.swing.JButton();
        jButtonNovoO = new javax.swing.JButton();
        jButtonEditarO = new javax.swing.JButton();
        jButtonExcluirO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOperario = new javax.swing.JTable();
        jTextFieldTelefone = new javax.swing.JFormattedTextField();
        jTextFieldDataNasc = new javax.swing.JFormattedTextField();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Operarios");
        setResizable(false);
        getContentPane().setLayout(null);

        jTextFieldCodigo.setEnabled(false);
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(140, 20, 40, 30);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNome.setText("Nome completo");
        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(140, 60, 200, 30);

        jTextFieldFiliacao.setEnabled(false);
        jTextFieldFiliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiliacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFiliacao);
        jTextFieldFiliacao.setBounds(140, 100, 200, 30);

        jTextFieldCargaHoraria.setEnabled(false);
        getContentPane().add(jTextFieldCargaHoraria);
        jTextFieldCargaHoraria.setBounds(140, 140, 200, 30);

        jTextFieldComissao.setEnabled(false);
        getContentPane().add(jTextFieldComissao);
        jTextFieldComissao.setBounds(140, 180, 200, 30);

        jTextFieldCargo.setEnabled(false);
        jTextFieldCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCargo);
        jTextFieldCargo.setBounds(140, 220, 200, 30);

        jTextFieldEndereco.setEnabled(false);
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(140, 300, 200, 30);

        jTextFieldDepartamento.setEnabled(false);
        getContentPane().add(jTextFieldDepartamento);
        jTextFieldDepartamento.setBounds(140, 340, 200, 30);

        jTextFieldSalario.setEnabled(false);
        getContentPane().add(jTextFieldSalario);
        jTextFieldSalario.setBounds(490, 20, 160, 30);

        jTextFieldSexo.setEnabled(false);
        getContentPane().add(jTextFieldSexo);
        jTextFieldSexo.setBounds(490, 60, 160, 30);

        jTextFieldHabilidades.setEnabled(false);
        getContentPane().add(jTextFieldHabilidades);
        jTextFieldHabilidades.setBounds(540, 340, 300, 30);

        jTextFieldTiposTrab.setEnabled(false);
        getContentPane().add(jTextFieldTiposTrab);
        jTextFieldTiposTrab.setBounds(640, 380, 200, 30);

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Codigo:");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(30, 20, 90, 30);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(30, 60, 70, 17);

        jLabelFiliacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFiliacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiliacao.setText("Filiação:");
        getContentPane().add(jLabelFiliacao);
        jLabelFiliacao.setBounds(30, 100, 100, 17);

        jLabelCargaHoraria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCargaHoraria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCargaHoraria.setText("Carga Horaria:");
        getContentPane().add(jLabelCargaHoraria);
        jLabelCargaHoraria.setBounds(30, 140, 120, 17);

        jLabelComissao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelComissao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComissao.setText("Comissao:");
        getContentPane().add(jLabelComissao);
        jLabelComissao.setBounds(30, 180, 80, 17);

        jLabelCargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCargo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCargo.setText("Cargo:");
        getContentPane().add(jLabelCargo);
        jLabelCargo.setBounds(30, 220, 50, 17);

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone:");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(30, 260, 70, 17);

        jLabelEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEndereco.setText("Endereço:");
        getContentPane().add(jLabelEndereco);
        jLabelEndereco.setBounds(40, 310, 70, 17);

        jLabelDepartamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDepartamento.setText("Departamento:");
        getContentPane().add(jLabelDepartamento);
        jLabelDepartamento.setBounds(30, 350, 105, 17);

        jLabelSalario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSalario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalario.setText("Salario: ");
        getContentPane().add(jLabelSalario);
        jLabelSalario.setBounds(440, 30, 70, 17);

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Sexo:");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(450, 70, 39, 17);

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNasc.setText("Data Nasc.:");
        getContentPane().add(jLabelDataNasc);
        jLabelDataNasc.setBounds(410, 100, 140, 17);

        jLabelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone-empresa.png"))); // NOI18N
        getContentPane().add(jLabelIcone);
        jLabelIcone.setBounds(830, 0, 230, 270);

        jLabelHabilidades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHabilidades.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHabilidades.setText("Habilidades:");
        getContentPane().add(jLabelHabilidades);
        jLabelHabilidades.setBounds(450, 350, 90, 17);

        jLabelTiposTrab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTiposTrab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiposTrab.setText("Tipos trabalhos executados:");
        getContentPane().add(jLabelTiposTrab);
        jLabelTiposTrab.setBounds(440, 390, 194, 17);

        jButtonSalvarO.setText("Salvar");
        jButtonSalvarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarO);
        jButtonSalvarO.setBounds(940, 300, 80, 23);

        jButtonCancelarO.setText("Cancelar");
        jButtonCancelarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarO);
        jButtonCancelarO.setBounds(850, 300, 80, 23);

        jButtonNovoO.setText("Novo");
        jButtonNovoO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoO);
        jButtonNovoO.setBounds(940, 340, 80, 23);

        jButtonEditarO.setText("Editar");
        jButtonEditarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarO);
        jButtonEditarO.setBounds(940, 450, 80, 23);

        jButtonExcluirO.setText("Excluir");
        jButtonExcluirO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirO);
        jButtonExcluirO.setBounds(850, 450, 70, 23);

        jTableOperario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOperario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOperarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOperario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 530, 1030, 250);

        try {
            jTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(140, 260, 200, 30);

        try {
            jTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataNascActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDataNasc);
        jTextFieldDataNasc.setBounds(490, 100, 160, 30);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tumblr_static_background.jpg"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(-20, -30, 1090, 870);

        setSize(new java.awt.Dimension(1071, 834));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jTextFieldFiliacaoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jTextFieldCargoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               
    /**
     * O evento do botão salvar é responsável por instanciar novos operarios e salva-lós conforme as informações 
     * passadas pelo usuário ou editar operarios que já foram instanciados anteriormente. Ele também verifica se
     * a data de nascimento fornecida pelo usuário é menor do que a estabelecida (01/01/1994), caso seja menor
     * a edição ou o salvamento é permitido. Para fazer isso é invocado o método SalvarOperario da camada Controller.
     * Após realizada as operações todos os campos são limpos e desabilitados.
     * @param evt Evento do botão salvar
     */
    private void jButtonSalvarOActionPerformed(java.awt.event.ActionEvent evt) {                                               
          // TODO add your handling code here:
          data=jTextFieldDataNasc.getText();
          ValidaData c = new ValidaData(data, ValidaData.BarraSemHora);
         if (flag==1/*&& hoje.getTimestamp().getTime()>c.getTimestamp().getTime()*/){
         if (OperarioControll.SalvarOperario(Modelo3.getRowCount(),jTextFieldNome.getText(), jTextFieldFiliacao.getText(),
               Integer.parseInt(jTextFieldCargaHoraria.getText()),Double.parseDouble(jTextFieldComissao.getText()),
               jTextFieldCargo.getText(), jTextFieldTelefone.getText(), jTextFieldEndereco.getText(),
               Double.parseDouble(jTextFieldSalario.getText()),jTextFieldDepartamento.getText(),jTextFieldHabilidades.getText(),
               jTextFieldTiposTrab.getText(),jTextFieldDataNasc.getText(),jTextFieldSexo.getText())){
           this.LoadTableOperario();
           JOptionPane.showMessageDialog(this, "Operario salvo com sucesso!");      
       }
       else
           JOptionPane.showMessageDialog(this, "Erro ao salvar aluno!");
         }else{ if(flag==2/*&& hoje.getTimestamp().getTime()>c.getTimestamp().getTime()*/){if (OperarioControll.SalvarOperario(Integer.parseInt(jTextFieldCodigo.getText()),jTextFieldNome.getText(), jTextFieldFiliacao.getText(),
               Integer.parseInt(jTextFieldCargaHoraria.getText()),Double.parseDouble(jTextFieldComissao.getText()),
               jTextFieldCargo.getText(), jTextFieldTelefone.getText(), jTextFieldEndereco.getText(),
               Double.parseDouble(jTextFieldSalario.getText()),jTextFieldDepartamento.getText(),jTextFieldHabilidades.getText(),
               jTextFieldTiposTrab.getText(),jTextFieldDataNasc.getText(),jTextFieldSexo.getText())){
           this.LoadTableOperario();
           JOptionPane.showMessageDialog(this, "Operario salvo com sucesso!");      
       }
       else
           JOptionPane.showMessageDialog(this, "Erro ao salvar aluno!");
             
         }
         }    
           
        jTextFieldCodigo.setText("");    
        jTextFieldNome.setText("");
        jTextFieldFiliacao.setText("");
        jTextFieldCargaHoraria.setText("");
        jTextFieldComissao.setText("");
        jTextFieldCargo.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldDepartamento.setText("");
        jTextFieldSalario.setText("");
        jTextFieldSexo.setText("");
        jTextFieldDataNasc.setText("");
        jTextFieldHabilidades.setText("");
        jTextFieldTiposTrab.setText("");
        jTextFieldCodigo.setEnabled(false);    
        jTextFieldNome.setEnabled(false);
        jTextFieldFiliacao.setEnabled(false);
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldComissao.setEnabled(false);
        jTextFieldCargo.setEnabled(false);
        jTextFieldTelefone.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldDepartamento.setEnabled(false);
        jTextFieldSalario.setEnabled(false);
        jTextFieldSexo.setEnabled(false);
        jTextFieldDataNasc.setEnabled(false);
        jTextFieldHabilidades.setEnabled(false);
        jTextFieldTiposTrab.setEnabled(false);
        Botoes(true,false,false,false,false);
        
        
    }   
    /**
     * O evento do botão cancelar é responsavel por limpar todos os campos necessários e desabitá-los.
     * @param evt evento do botão cancelar
     */

    private void jButtonCancelarOActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        jTextFieldCodigo.setText("");    
        jTextFieldNome.setText("");
        jTextFieldFiliacao.setText("");
        jTextFieldCargaHoraria.setText("");
        jTextFieldComissao.setText("");
        jTextFieldCargo.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldDepartamento.setText("");
        jTextFieldSalario.setText("");
        jTextFieldSexo.setText("");
        jTextFieldDataNasc.setText("");
        jTextFieldHabilidades.setText("");
        jTextFieldTiposTrab.setText("");
        jTextFieldCodigo.setEnabled(false);    
        jTextFieldNome.setEnabled(false);
        jTextFieldFiliacao.setEnabled(false);
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldComissao.setEnabled(false);
        jTextFieldCargo.setEnabled(false);
        jTextFieldTelefone.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldDepartamento.setEnabled(false);
        jTextFieldSalario.setEnabled(false);
        jTextFieldSexo.setEnabled(false);
        jTextFieldDataNasc.setEnabled(false);
        jTextFieldHabilidades.setEnabled(false);
        jTextFieldTiposTrab.setEnabled(false);
              
       Botoes(true,false,false,false,false);
    }              
    /**
     * O evento do botão novo é responsável por limpar todos os campos e atribuir as visibilidades necessárias. 
     * @param evt Evento do Botao Novo
     */

    private void jButtonNovoOActionPerformed(java.awt.event.ActionEvent evt) {                                             
         // TODO add your handling code here:
         flag=1;
        jTextFieldCodigo.setText("");    
        jTextFieldNome.setText("");
        jTextFieldFiliacao.setText("");
        jTextFieldCargaHoraria.setText("");
        jTextFieldComissao.setText("");
        jTextFieldCargo.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldDepartamento.setText("");
        jTextFieldSalario.setText("");
        jTextFieldSexo.setText("");
        jTextFieldDataNasc.setText("");
        jTextFieldHabilidades.setText("");
        jTextFieldTiposTrab.setText(""); 
        jTextFieldCodigo.setEnabled(false);    
        jTextFieldNome.setEnabled(true);
        jTextFieldFiliacao.setEnabled(true);
        jTextFieldCargaHoraria.setEnabled(true);
        jTextFieldComissao.setEnabled(true);
        jTextFieldCargo.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldDepartamento.setEnabled(true);
        jTextFieldSalario.setEnabled(true);
        jTextFieldSexo.setEnabled(true);
        jTextFieldDataNasc.setEnabled(true);
        jTextFieldHabilidades.setEnabled(true);
        jTextFieldTiposTrab.setEnabled(true);
        Botoes(false,false,false,true,true);
    }
    /**
     * O evento do botão excluir é responsável por excluir algum Operario que já tenha sido anteriormente 
     * instanciado. Para isso ele invoca o metodo SalvarOperario da camada Controller. Após excluí-lo o evento
     * atualiza a tabela com a respectiva ação.
     * @param evt Evento do Botao Excluir
     */

    private void jButtonExcluirOActionPerformed(java.awt.event.ActionEvent evt) {                                                
         // TODO add your handling code here:
         flag=3;
         if (OperarioControll.SalvarOperario(Modelo3.getRowCount(),jTextFieldNome.getText(), jTextFieldFiliacao.getText(),
               Integer.parseInt(jTextFieldCargaHoraria.getText()),Double.parseDouble(jTextFieldComissao.getText()),
               jTextFieldCargo.getText(), jTextFieldTelefone.getText(), jTextFieldEndereco.getText(),
               Double.parseDouble(jTextFieldSalario.getText()),jTextFieldDepartamento.getText(),jTextFieldHabilidades.getText(),
               jTextFieldTiposTrab.getText(),jTextFieldDataNasc.getText(),jTextFieldSexo.getText())){
           this.LoadTableOperario();
           JOptionPane.showMessageDialog(this, "Operario excluído com sucesso!");      
       }
         jTextFieldCodigo.setText("");    
        jTextFieldNome.setText("");
        jTextFieldFiliacao.setText("");
        jTextFieldCargaHoraria.setText("");
        jTextFieldComissao.setText("");
        jTextFieldCargo.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldDepartamento.setText("");
        jTextFieldSalario.setText("");
        jTextFieldSexo.setText("");
        jTextFieldDataNasc.setText("");
        jTextFieldHabilidades.setText("");
        jTextFieldTiposTrab.setText(""); 
         Botoes(true,false,false,false,false);       
    }                                               
    /**
     * O evento do jTableOperarioMouseClicked é responsável por carregar as informações da tabela nos respectivos
     * campos.
     * @param evt evento mouse clicked da tabela
     */
    private void jTableOperarioMouseClicked(java.awt.event.MouseEvent evt) {                                            
         // TODO add your handling code here:
         flag=3;
        Botoes(true,true,true,false,false);
        index = jTableOperario.getSelectedRow();
        if(index>=0 && index<Modelo3.getRowCount()){
            String temp[] = Modelo3.getOperarios(index);            
        jTextFieldCodigo.setText(temp[0]);  
        jTextFieldNome.setText(temp[1]);
        jTextFieldFiliacao.setText(temp[2]);
        jTextFieldCargaHoraria.setText(temp[3]);
        jTextFieldComissao.setText(temp[4]);
        jTextFieldCargo.setText(temp[5]);
        jTextFieldTelefone.setText(temp[6]);
        jTextFieldEndereco.setText(temp[7]);
        jTextFieldSalario.setText(temp[8]);
        jTextFieldDepartamento.setText(temp[9]);
        jTextFieldHabilidades.setText(temp[10]);
        jTextFieldTiposTrab.setText(temp[11]);
        jTextFieldDataNasc.setText(temp[12]);
        jTextFieldSexo.setText(temp[13]);
        }
         
    }                                           

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jTextFieldDataNascActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  
    /**
     * O evento do botão editar é responsável por atribuir as visibilidades dos campos conforme a necessidade.
     * @param evt Evento do Botao Editar
     */
    private void jButtonEditarOActionPerformed(java.awt.event.ActionEvent evt) {                                               
         // TODO add your handling code here:
         flag=2;
        jTextFieldCodigo.setEnabled(false);    
        jTextFieldNome.setEnabled(true);
        jTextFieldFiliacao.setEnabled(true);
        jTextFieldCargaHoraria.setEnabled(true);
        jTextFieldComissao.setEnabled(true);
        jTextFieldCargo.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldDepartamento.setEnabled(true);
        jTextFieldSalario.setEnabled(true);
        jTextFieldSexo.setEnabled(true);
        jTextFieldDataNasc.setEnabled(true);
        jTextFieldHabilidades.setEnabled(true);
        jTextFieldTiposTrab.setEnabled(true);
        Botoes(false,false,false,true,true);     
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCadastroOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCadastroOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCadastroOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCadastroOperario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCadastroOperario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel FUNDO;
    private javax.swing.JButton jButtonCancelarO;
    private javax.swing.JButton jButtonEditarO;
    private javax.swing.JButton jButtonExcluirO;
    private javax.swing.JButton jButtonNovoO;
    private javax.swing.JButton jButtonSalvarO;
    private javax.swing.JLabel jLabelCargaHoraria;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelComissao;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelFiliacao;
    private javax.swing.JLabel jLabelHabilidades;
    private javax.swing.JLabel jLabelIcone;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTiposTrab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOperario;
    private javax.swing.JTextField jTextFieldCargaHoraria;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldComissao;
    private javax.swing.JFormattedTextField jTextFieldDataNasc;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldFiliacao;
    private javax.swing.JTextField jTextFieldHabilidades;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JFormattedTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldTiposTrab;
    // End of variables declaration                   
}
