/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GerenteControll;
import Controller.ProjetoControll;
import Model.Projeto;
import TableModel.GerenteTM;
import Util.ValidaData;

import java.util.List;
import javax.swing.JOptionPane;

/**
 * A classe TCadastroGerente estende as características de javax.swing.JFrame, portanto ela é uma classe de interface
 * gráfica com interação com o usuario e é responsável por receber os dados que vão ser atríbutos a cada novo
 * Gerente criado, editar ou excluir gerentes já instanciados.
 * @author Pedro Henrique 
 * @version 3.0 (nov. 2020)
 */
public class TCadastroGerente extends javax.swing.JFrame {
	//atributos
    private String data;
    private ValidaData hoje= new ValidaData("01/01/1994",ValidaData.BarraSemHora);
    public static int index;
    public static int flag;
    private GerenteTM Modelo;
    /**
     * O metodo LoadTableGerente 3 é responsável por carregar a tabela de Gerentes todas as vezes que alguma 
     * alteração for realizada.
     */
    public void LoadTableGeren3(){
         Modelo= new GerenteTM(GerenteControll.getGerentes());
         tbl_gerentes.setModel(Modelo);   
         this.LoadCBProjs();
     }
    /**
     * O método Botoes é responsável por ditar a visibilidade de todos os botões presentes na classe.
     * @param N botao Novo
     * @param E botao Editar
     * @param R Botao Excluir
     * @param S Botao Salvar
     * @param C Botao Cancelar
     * 
     */
     public void Botoes(boolean N, boolean E, boolean R, boolean S, boolean C){
        jButtonNovo3.setEnabled(N);
        jButtonEditar3.setEnabled(E);
        jButtonExcluir3.setEnabled(R);
        jButtonSalvar3.setEnabled(S);
        jButtonCancelar3.setEnabled(C);        
    }
     /**
      * O metodo LoadCBProjs é reponsável por carregar o ComboBox de projetos com o nome de todos os projetos
      * que já foram instanciados.
      * 
      */
     
     public void LoadCBProjs(){
    	jComboBoxProjetos.removeAllItems();
        jComboBoxProjetos.addItem("Null");
    	List<Projeto> listaDeProjetos=Projeto.getProjeto();
        if(ProjetoControll.getProjetos().size()!=0){
    	for(Projeto projetos: listaDeProjetos) {   	
    	jComboBoxProjetos.addItem(projetos.toString());
        }
    	}    	
    }
         /**
          * O construtor da classe é responsável por carregar todos os componentes ou ações que a classe deve 
          * realizar quando for iniciada.
          *      
          */
    public TCadastroGerente() {
        initComponents();
        //ListaGeren=new ArrayList();
        setLocationRelativeTo(null);
        LoadTableGeren3();
        LoadCBProjs();
        Botoes(true,false,false,false,false);
        jComboBoxProjetos.setEnabled(false);
        jTextFieldCodigoG3.setEnabled(false);    
        jTextFieldNomeG3.setEnabled(false);
        jTextFieldFiliacaoG3.setEnabled(false);
        jTextFieldCargaHorariaG3.setEnabled(false);
        jTextFieldComissaoG3.setEnabled(false);
        jTextFieldCargoG3.setEnabled(false);
        jTextFieldTelefoneG3.setEnabled(false);
        jTextFieldEnderecoG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldDepartamentoG3.setEnabled(false);
        jTextFieldSexoG3.setEnabled(false);
        jTextFieldDataNascG3.setEnabled(false);
    }
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelCodigoG = new javax.swing.JLabel();
        jLabelNomeG = new javax.swing.JLabel();
        jTextFieldNomeG3 = new javax.swing.JTextField();
        jLabelFiliacaoG = new javax.swing.JLabel();
        jTextFieldFiliacaoG3 = new javax.swing.JTextField();
        jLabelCargaHorariaG = new javax.swing.JLabel();
        jTextFieldCargaHorariaG3 = new javax.swing.JTextField();
        jLabelComissaoG = new javax.swing.JLabel();
        jTextFieldComissaoG3 = new javax.swing.JTextField();
        jLabelCargoG = new javax.swing.JLabel();
        jTextFieldCargoG3 = new javax.swing.JTextField();
        jLabelTelefoneG = new javax.swing.JLabel();
        jLabelEnderecoG = new javax.swing.JLabel();
        jTextFieldEnderecoG3 = new javax.swing.JTextField();
        jLabelDepartamentoG = new javax.swing.JLabel();
        jTextFieldDepartamentoG3 = new javax.swing.JTextField();
        jLabelSalarioG = new javax.swing.JLabel();
        jTextFieldSalarioG3 = new javax.swing.JTextField();
        jLabelSexoG = new javax.swing.JLabel();
        jTextFieldSexoG3 = new javax.swing.JTextField();
        jLabelDataNascG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar3 = new javax.swing.JButton();
        jButtonNovo3 = new javax.swing.JButton();
        jButtonSalvar3 = new javax.swing.JButton();
        jButtonEditar3 = new javax.swing.JButton();
        jButtonExcluir3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_gerentes = new javax.swing.JTable();
        jTextFieldDataNascG3 = new javax.swing.JFormattedTextField();
        jTextFieldTelefoneG3 = new javax.swing.JFormattedTextField();
        jTextFieldCodigoG3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProjetos = new javax.swing.JComboBox<>();
        FUNDO1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Gerente");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCodigoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCodigoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoG.setText("Codigo:");
        getContentPane().add(jLabelCodigoG);
        jLabelCodigoG.setBounds(20, 10, 90, 30);

        jLabelNomeG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeG.setText("Nome:");
        getContentPane().add(jLabelNomeG);
        jLabelNomeG.setBounds(20, 50, 70, 17);

        jTextFieldNomeG3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNomeG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeG3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeG3);
        jTextFieldNomeG3.setBounds(130, 50, 200, 30);

        jLabelFiliacaoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFiliacaoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiliacaoG.setText("Filiação:");
        getContentPane().add(jLabelFiliacaoG);
        jLabelFiliacaoG.setBounds(20, 90, 100, 17);

        jTextFieldFiliacaoG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiliacaoG3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFiliacaoG3);
        jTextFieldFiliacaoG3.setBounds(130, 90, 200, 30);

        jLabelCargaHorariaG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCargaHorariaG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCargaHorariaG.setText("Carga Horaria:");
        getContentPane().add(jLabelCargaHorariaG);
        jLabelCargaHorariaG.setBounds(20, 130, 120, 17);
        getContentPane().add(jTextFieldCargaHorariaG3);
        jTextFieldCargaHorariaG3.setBounds(130, 130, 200, 30);

        jLabelComissaoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelComissaoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComissaoG.setText("Comissao:");
        getContentPane().add(jLabelComissaoG);
        jLabelComissaoG.setBounds(20, 170, 80, 17);
        getContentPane().add(jTextFieldComissaoG3);
        jTextFieldComissaoG3.setBounds(130, 170, 200, 30);

        jLabelCargoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCargoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCargoG.setText("Cargo:");
        getContentPane().add(jLabelCargoG);
        jLabelCargoG.setBounds(20, 210, 50, 17);

        jTextFieldCargoG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargoG3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCargoG3);
        jTextFieldCargoG3.setBounds(130, 210, 200, 30);

        jLabelTelefoneG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTelefoneG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefoneG.setText("Telefone:");
        getContentPane().add(jLabelTelefoneG);
        jLabelTelefoneG.setBounds(20, 250, 70, 17);

        jLabelEnderecoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEnderecoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnderecoG.setText("Endereço:");
        getContentPane().add(jLabelEnderecoG);
        jLabelEnderecoG.setBounds(30, 300, 70, 17);
        getContentPane().add(jTextFieldEnderecoG3);
        jTextFieldEnderecoG3.setBounds(130, 290, 200, 30);

        jLabelDepartamentoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDepartamentoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDepartamentoG.setText("Departamento:");
        getContentPane().add(jLabelDepartamentoG);
        jLabelDepartamentoG.setBounds(20, 340, 105, 17);
        getContentPane().add(jTextFieldDepartamentoG3);
        jTextFieldDepartamentoG3.setBounds(130, 330, 200, 30);

        jLabelSalarioG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSalarioG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalarioG.setText("Salario: ");
        getContentPane().add(jLabelSalarioG);
        jLabelSalarioG.setBounds(430, 10, 70, 17);
        getContentPane().add(jTextFieldSalarioG3);
        jTextFieldSalarioG3.setBounds(480, 10, 160, 30);

        jLabelSexoG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSexoG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexoG.setText("Sexo:");
        getContentPane().add(jLabelSexoG);
        jLabelSexoG.setBounds(440, 50, 39, 17);

        jTextFieldSexoG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexoG3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSexoG3);
        jTextFieldSexoG3.setBounds(480, 50, 160, 30);

        jLabelDataNascG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDataNascG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNascG.setText("Data Nasc.:");
        getContentPane().add(jLabelDataNascG);
        jLabelDataNascG.setBounds(400, 90, 78, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone-empresa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(670, -20, 212, 270);

        jButtonCancelar3.setText("Cancelar");
        jButtonCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar3);
        jButtonCancelar3.setBounds(800, 260, 80, 23);

        jButtonNovo3.setText("Novo");
        jButtonNovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo3);
        jButtonNovo3.setBounds(720, 260, 70, 23);

        jButtonSalvar3.setText("Salvar");
        jButtonSalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar3);
        jButtonSalvar3.setBounds(720, 300, 70, 23);

        jButtonEditar3.setText("Editar");
        jButtonEditar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditar3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar3);
        jButtonEditar3.setBounds(800, 300, 80, 23);

        jButtonExcluir3.setText("Excluir");
        jButtonExcluir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir3);
        jButtonExcluir3.setBounds(800, 350, 63, 23);

        tbl_gerentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Filiação", "Carga Horaria", "Comissão", "Cargo", "Telefone", "Endereço", "Departamento", "Salário", "Sexo", "Data Nasc."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_gerentes.getTableHeader().setReorderingAllowed(false);
        tbl_gerentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gerentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_gerentes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 460, 1000, 320);

        try {
            jTextFieldDataNascG3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTextFieldDataNascG3);
        jTextFieldDataNascG3.setBounds(480, 90, 160, 30);

        try {
            jTextFieldTelefoneG3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTextFieldTelefoneG3);
        jTextFieldTelefoneG3.setBounds(130, 250, 200, 30);
        getContentPane().add(jTextFieldCodigoG3);
        jTextFieldCodigoG3.setBounds(130, 10, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Projetos Gerenciados:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 180, 140, 15);

        jComboBoxProjetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null" }));
        getContentPane().add(jComboBoxProjetos);
        jComboBoxProjetos.setBounds(480, 180, 160, 30);

        FUNDO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tumblr_static_background.jpg"))); // NOI18N
        getContentPane().add(FUNDO1);
        FUNDO1.setBounds(0, -40, 1170, 880);

        setSize(new java.awt.Dimension(1046, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jTextFieldNomeG3ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void jTextFieldFiliacaoG3ActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void jTextFieldCargoG3ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jTextFieldSexoG3ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                
    /**
     * O evento do botão salvar é responsável por instanciar novos gerentes e salva-lós conforme as informações 
     * passadas pelo usuário ou editar operarios que já foram instanciados anteriormente. Ele também verifica se
     * a data de nascimento fornecida pelo usuário é menor do que a estabelecida (01/01/1994), caso seja menor
     * a edição ou o salvamento é permitido. Para fazer isso é invocado o método SalvarGerente da camada Controller.
     * Após realizada as operações todos os campos são limpos e desabilitados.
     * @param evt Evento do botão salvar
     */
    private void jButtonSalvar3ActionPerformed(java.awt.event.ActionEvent evt) {                                               
         // TODO add your handling code here:
         data=jTextFieldDataNascG3.getText();
          ValidaData c = new ValidaData(data, ValidaData.BarraSemHora);
         if (flag==1/*&& hoje.getTimestamp().getTime()>c.getTimestamp().getTime()*/){if(GerenteControll.SalvarGerente(Modelo.getRowCount(),jTextFieldNomeG3.getText(), jTextFieldFiliacaoG3.getText(),
               Integer.parseInt(jTextFieldCargaHorariaG3.getText()),Float.parseFloat(jTextFieldComissaoG3.getText()),
               jTextFieldCargoG3.getText(), jTextFieldTelefoneG3.getText(), jTextFieldEnderecoG3.getText(),
               Float.parseFloat(jTextFieldSalarioG3.getText()),jTextFieldDepartamentoG3.getText(), jTextFieldSexoG3.getText(),
               jTextFieldDataNascG3.getText(),(String) jComboBoxProjetos.getSelectedItem())){
           this.LoadTableGeren3();
           JOptionPane.showMessageDialog(this, "Gerente salvo com sucesso!");      
       }
       else
           JOptionPane.showMessageDialog(this, "Erro ao salvar aluno!");
         }else
             if (flag==2/*&& hoje.getTimestamp().getTime()>c.getTimestamp().getTime()*/){if(GerenteControll.SalvarGerente(Modelo.getRowCount(),jTextFieldNomeG3.getText(), jTextFieldFiliacaoG3.getText(),
               Integer.parseInt(jTextFieldCargaHorariaG3.getText()),Float.parseFloat(jTextFieldComissaoG3.getText()),
               jTextFieldCargoG3.getText(), jTextFieldTelefoneG3.getText(), jTextFieldEnderecoG3.getText(),
               Float.parseFloat(jTextFieldSalarioG3.getText()),jTextFieldDepartamentoG3.getText(), jTextFieldSexoG3.getText(),
               jTextFieldDataNascG3.getText(),(String) jComboBoxProjetos.getSelectedItem())){
           this.LoadTableGeren3();
           JOptionPane.showMessageDialog(this, "Gerente salvo com sucesso!");      
       }
       else
           JOptionPane.showMessageDialog(this, "Erro ao salvar aluno!");                 
             }
         
        jTextFieldCodigoG3.setText("");    
        jTextFieldNomeG3.setText("");
        jTextFieldFiliacaoG3.setText("");
        jTextFieldCargaHorariaG3.setText("");
        jTextFieldComissaoG3.setText("");
        jTextFieldCargoG3.setText("");
        jTextFieldTelefoneG3.setText("");
        jTextFieldEnderecoG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldDepartamentoG3.setText("");
        jTextFieldSexoG3.setText("");
        jTextFieldDataNascG3.setText("");
        jTextFieldCodigoG3.setEnabled(false);    
        jTextFieldNomeG3.setEnabled(false);
        jTextFieldFiliacaoG3.setEnabled(false);
        jTextFieldCargaHorariaG3.setEnabled(false);
        jTextFieldComissaoG3.setEnabled(false);
        jTextFieldCargoG3.setEnabled(false);
        jTextFieldTelefoneG3.setEnabled(false);
        jTextFieldEnderecoG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldDepartamentoG3.setEnabled(false);
        jTextFieldSexoG3.setEnabled(false);
        jTextFieldDataNascG3.setEnabled(false);  
        Botoes(true,false,false,false,false);              
    }        
    /**
     * O evento do botão cancelar é responsavel por limpar todos os campos necessários e desabitá-los.
     * @param evt evento do botão cancelar
     */

    private void jButtonCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
         // TODO add your handling code here:
         
        jTextFieldCodigoG3.setText("");    
        jTextFieldNomeG3.setText("");
        jTextFieldFiliacaoG3.setText("");
        jTextFieldCargaHorariaG3.setText("");
        jTextFieldComissaoG3.setText("");
        jTextFieldCargoG3.setText("");
        jTextFieldTelefoneG3.setText("");
        jTextFieldEnderecoG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldDepartamentoG3.setText("");
        jTextFieldSexoG3.setText("");
        jTextFieldDataNascG3.setText("");
        jTextFieldCodigoG3.setEnabled(false);    
        jTextFieldNomeG3.setEnabled(false);
        jTextFieldFiliacaoG3.setEnabled(false);
        jTextFieldCargaHorariaG3.setEnabled(false);
        jTextFieldComissaoG3.setEnabled(false);
        jTextFieldCargoG3.setEnabled(false);
        jTextFieldTelefoneG3.setEnabled(false);
        jTextFieldEnderecoG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldDepartamentoG3.setEnabled(false);
        jTextFieldSexoG3.setEnabled(false);
        jTextFieldDataNascG3.setEnabled(false);         
       Botoes(true,false,false,false,false);
    }                                                
    /**
     * O evento do botão editar é responsável por atribuir as visibilidades dos campos conforme a necessidade.
     * @param evt Evento do Botao Editar
     */
    
    private void jButtonEditar3ActionPerformed(java.awt.event.ActionEvent evt) {                                               
          // TODO add your handling code here:
         flag=2;
        jTextFieldCodigoG3.setEnabled(false);    
        jTextFieldNomeG3.setEnabled(true);
        jTextFieldFiliacaoG3.setEnabled(true);
        jTextFieldCargaHorariaG3.setEnabled(true);
        jTextFieldComissaoG3.setEnabled(true);
        jTextFieldCargoG3.setEnabled(true);
        jTextFieldTelefoneG3.setEnabled(true);
        jTextFieldEnderecoG3.setEnabled(true);
        jTextFieldSalarioG3.setEnabled(true);
        jTextFieldSalarioG3.setEnabled(true);
        jTextFieldDepartamentoG3.setEnabled(true);
        jTextFieldSexoG3.setEnabled(true);
        jTextFieldDataNascG3.setEnabled(true);
        jComboBoxProjetos.setEnabled(true);
        Botoes(false,false,false,true,true);
    }                                              
    /**
     * O evento do botão novo é responsável por limpar todos os campos e atribuir as visibilidades necessárias. 
     * @param evt Evento do Botao Novo
     */
    
    private void jButtonNovo3ActionPerformed(java.awt.event.ActionEvent evt) {                                             
         // TODO add your handling code here: 
        flag=1;
        jTextFieldCodigoG3.setText("");    
        jTextFieldNomeG3.setText("");
        jTextFieldFiliacaoG3.setText("");
        jTextFieldCargaHorariaG3.setText("");
        jTextFieldComissaoG3.setText("");
        jTextFieldCargoG3.setText("");
        jTextFieldTelefoneG3.setText("");
        jTextFieldEnderecoG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldDepartamentoG3.setText("");
        jTextFieldSexoG3.setText("");
        jTextFieldDataNascG3.setText("");  
        jTextFieldCodigoG3.setEnabled(false);    
        jTextFieldNomeG3.setEnabled(true);
        jTextFieldFiliacaoG3.setEnabled(true);
        jTextFieldCargaHorariaG3.setEnabled(true);
        jTextFieldComissaoG3.setEnabled(true);
        jTextFieldCargoG3.setEnabled(true);
        jTextFieldTelefoneG3.setEnabled(true);
        jTextFieldEnderecoG3.setEnabled(true);
        jTextFieldSalarioG3.setEnabled(true);
        jTextFieldSalarioG3.setEnabled(true);
        jTextFieldDepartamentoG3.setEnabled(true);
        jTextFieldSexoG3.setEnabled(true);
        jTextFieldDataNascG3.setEnabled(true);
        Botoes(false,false,false,true,true);
    }                    
    /**
     * O evento do botão excluir é responsável por excluir algum Gerente que já tenha sido anteriormente 
     * instanciado. Para isso ele invoca o metodo SalvarGerente da camada Controller. Após excluí-lo o evento
     * atualiza a tabela com a respectiva ação.
     * @param evt Evento do Botao Excluir
     */

    private void jButtonExcluir3ActionPerformed(java.awt.event.ActionEvent evt) {                                                
          // TODO add your handling code here:
         flag=3;
         if(GerenteControll.SalvarGerente(Modelo.getRowCount(),jTextFieldNomeG3.getText(), jTextFieldFiliacaoG3.getText(),
               Integer.parseInt(jTextFieldCargaHorariaG3.getText()),Float.parseFloat(jTextFieldComissaoG3.getText()),
               jTextFieldCargoG3.getText(), jTextFieldTelefoneG3.getText(), jTextFieldEnderecoG3.getText(),
               Float.parseFloat(jTextFieldSalarioG3.getText()),jTextFieldDepartamentoG3.getText(), jTextFieldSexoG3.getText(),
               jTextFieldDataNascG3.getText(),(String) jComboBoxProjetos.getSelectedItem())){
           this.LoadTableGeren3();
           JOptionPane.showMessageDialog(this, "Gerente excluído com sucesso!");      
       }
         jTextFieldCodigoG3.setText("");    
        jTextFieldNomeG3.setText("");
        jTextFieldFiliacaoG3.setText("");
        jTextFieldCargaHorariaG3.setText("");
        jTextFieldComissaoG3.setText("");
        jTextFieldCargoG3.setText("");
        jTextFieldTelefoneG3.setText("");
        jTextFieldEnderecoG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldSalarioG3.setText("");
        jTextFieldDepartamentoG3.setText("");
        jTextFieldSexoG3.setText("");
        jTextFieldDataNascG3.setText("");
        
         Botoes(true,false,false,true,false);
    }            
    /**
     * O evento do tbl_gerentesMouseClicked é responsável por carregar as informações da tabela nos respectivos
     * campos.
     * @param evt evento mouse clicked da tabela
     */

    private void tbl_gerentesMouseClicked(java.awt.event.MouseEvent evt) {                                          
        flag=3;
        Botoes(true,true,true,false,false);
        index = tbl_gerentes.getSelectedRow();
        if(index>=0 && index<Modelo.getRowCount()){
            String temp[] = Modelo.getGerentes(index);
            jTextFieldCodigoG3.setText(temp[0]);
            jTextFieldNomeG3.setText(temp[1]);
            jTextFieldFiliacaoG3.setText(temp[2]);
            jTextFieldCargaHorariaG3.setText(temp[3]);
            jTextFieldComissaoG3.setText(temp[4]);
            jTextFieldCargoG3.setText(temp[5]);
            jTextFieldTelefoneG3.setText(temp[6]);
            jTextFieldEnderecoG3.setText(temp[7]);
            jTextFieldSalarioG3.setText(temp[8]);
            jTextFieldDepartamentoG3.setText(temp[6]);
            jTextFieldSexoG3.setText(temp[10]);
            jTextFieldDataNascG3.setText(temp[11]);
        }
        jTextFieldCodigoG3.setEnabled(false);    
        jTextFieldNomeG3.setEnabled(false);
        jTextFieldFiliacaoG3.setEnabled(false);
        jTextFieldCargaHorariaG3.setEnabled(false);
        jTextFieldComissaoG3.setEnabled(false);
        jTextFieldCargoG3.setEnabled(false);
        jTextFieldTelefoneG3.setEnabled(false);
        jTextFieldEnderecoG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldSalarioG3.setEnabled(false);
        jTextFieldDepartamentoG3.setEnabled(false);
        jTextFieldSexoG3.setEnabled(false);
        jTextFieldDataNascG3.setEnabled(false);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCadastroGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel FUNDO1;
    private javax.swing.JButton jButtonCancelar3;
    private javax.swing.JButton jButtonEditar3;
    private javax.swing.JButton jButtonExcluir3;
    private javax.swing.JButton jButtonNovo3;
    private javax.swing.JButton jButtonSalvar3;
    private javax.swing.JComboBox<String> jComboBoxProjetos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCargaHorariaG;
    private javax.swing.JLabel jLabelCargoG;
    private javax.swing.JLabel jLabelCodigoG;
    private javax.swing.JLabel jLabelComissaoG;
    private javax.swing.JLabel jLabelDataNascG;
    private javax.swing.JLabel jLabelDepartamentoG;
    private javax.swing.JLabel jLabelEnderecoG;
    private javax.swing.JLabel jLabelFiliacaoG;
    private javax.swing.JLabel jLabelNomeG;
    private javax.swing.JLabel jLabelSalarioG;
    private javax.swing.JLabel jLabelSexoG;
    private javax.swing.JLabel jLabelTelefoneG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCargaHorariaG3;
    private javax.swing.JTextField jTextFieldCargoG3;
    private javax.swing.JTextField jTextFieldCodigoG3;
    private javax.swing.JTextField jTextFieldComissaoG3;
    private javax.swing.JFormattedTextField jTextFieldDataNascG3;
    private javax.swing.JTextField jTextFieldDepartamentoG3;
    private javax.swing.JTextField jTextFieldEnderecoG3;
    private javax.swing.JTextField jTextFieldFiliacaoG3;
    private javax.swing.JTextField jTextFieldNomeG3;
    private javax.swing.JTextField jTextFieldSalarioG3;
    private javax.swing.JTextField jTextFieldSexoG3;
    private javax.swing.JFormattedTextField jTextFieldTelefoneG3;
    private javax.swing.JTable tbl_gerentes;
    // End of variables declaration                   
}
