/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 * A classe login estende as caracteristicas de javax.swing.JFrame, ou seja, ela é uma interface gráfica de interação
 * com o usuário, sendo a primeira tela aprensetada.
 * @author Pedro Henrique
 * version 3.0 (nov. 2020)
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelLoguin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUSUARIOA = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        lblUSUARIO1 = new javax.swing.JLabel();
        lblSENHA = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Login");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLoguin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone-empresa.png"))); // NOI18N
        getContentPane().add(jLabelLoguin);
        jLabelLoguin.setBounds(20, 10, 260, 270);

        jLabel2.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gerenciamento Empresarial");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 60, 270, 22);

        lblUSUARIOA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUSUARIOA.setForeground(new java.awt.Color(255, 255, 255));
        lblUSUARIOA.setText("Usuario: Usuario, senha:6789");
        getContentPane().add(lblUSUARIOA);
        lblUSUARIOA.setBounds(170, 250, 210, 40);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(349, 120, 140, 30);

        lblUSUARIO1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUSUARIO1.setForeground(new java.awt.Color(255, 255, 255));
        lblUSUARIO1.setText("Usuario:");
        getContentPane().add(lblUSUARIO1);
        lblUSUARIO1.setBounds(280, 110, 100, 40);

        lblSENHA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSENHA.setForeground(new java.awt.Color(255, 255, 255));
        lblSENHA.setText("Senha:");
        getContentPane().add(lblSENHA);
        lblSENHA.setBounds(280, 160, 60, 40);

        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(350, 170, 140, 30);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(323, 220, 70, 23);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(420, 220, 70, 23);

        FUNDO.setDisplayedMnemonic('T');
        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tumblr_static_background.jpg"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(0, 0, 570, 310);

        setSize(new java.awt.Dimension(576, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {                                               

        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        if(jTextFieldUsuario.getText().equals
("Usuario")&&jPasswordFieldSenha.getText().equals("6789")){
TelaPrincipal tela=new TelaPrincipal();
		tela.setVisible(true);
	dispose();
}
	else{
	JOptionPane.showMessageDialog(rootPane, "Acesso Negado!");
}
    }                                              

    
    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                              
          if(jTextFieldUsuario.getText().equals
("Usuario")&&jPasswordFieldSenha.getText().equals("6789")){
TelaPrincipal tela=new TelaPrincipal();
		tela.setVisible(true);
	dispose();
}
	else{
	JOptionPane.showMessageDialog(rootPane, "Acesso Negado!");
}
    }                                             

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {                                            
        System.exit(0);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel FUNDO;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLoguin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel lblSENHA;
    private javax.swing.JLabel lblUSUARIO1;
    private javax.swing.JLabel lblUSUARIOA;
    // End of variables declaration                   
}
