/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TrabalhoControl;
import Model.Operario;
import TableModel.TrabalhoTM;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * A classe TNovoTrabalho estende as características de javax.swing.JFrame, portanto ela é uma classe de interface
 * gráfica com interação com o usuario e é responsável por receber os dados que vão ser atríbutos a cada novo
 * Trabalho criado, editar ou excluir trabalhos já instanciados.
 * @author Pedro Henrique 
 * @version 3.0 (nov. 2020)
 */

public class TNovoTrabalho extends javax.swing.JFrame {
	//atributos
    public static int flag=0;
    private TrabalhoTM Modelo4;
    public static int index;
   
    /**
     * O método LoadTableaTrab é responsável por carregar as alterações na tabela de trabalhos toda vez que houver
     * alguma mudança
     */
    public void LoadTableTrab(){    	
         Modelo4= new TrabalhoTM(TrabalhoControl.getTrabalhos());
         jTableTrab.setModel(Modelo4);   
         LoadCBTrab();
     }
    /**
     * O metodo LoadCBTrab é responsável por carregar o nome de todos os operarios que já foram instanciados dentro
     * do ComboBox de operarios 1.
     */
    public void LoadCBTrab() {
    	jComboBoxOp1.removeAllItems();  
    	
    	List<Operario> listaDeOperarios1=Operario.getOperarios();
        jComboBoxOp1.addItem("Selecione");
    	for(Operario operarios: listaDeOperarios1) {           
    	jComboBoxOp1.addItem(operarios.toString());        
        }     
    }
    /**
     * O metodo LoadCBTrab2 é responsável por carregar o nome de todos os operarios que já foram instanciados dentro
     * do ComboBox de operarios 2.
     */
          
    public void LoadCBTrab2(){
        jComboBoxOp2.removeAllItems(); 
        List<Operario> listaDeOperarios2=Operario.getOperarios();
        jComboBoxOp2.addItem("Selecione");
    	for(Operario operarios: listaDeOperarios2) {
    	jComboBoxOp2.addItem(operarios.toString());  	
        }     
    }
    /**
     * O metodo LoadCBTrab3 é responsável por carregar o nome de todos os operarios que já foram instanciados dentro
     * do ComboBox de operarios 3.
     */
    public void LoadCBTrab3(){
        jComboBoxOp3.removeAllItems(); 
        List<Operario> listaDeOperarios3=Operario.getOperarios();
        jComboBoxOp3.addItem("Selecione");
    	for(Operario operarios: listaDeOperarios3) {   	
    	jComboBoxOp3.addItem(operarios.toString());  	
        }     
    }
    /**
     * O metodo LoadCBTrab4 é responsável por carregar o nome de todos os operarios que já foram instanciados dentro
     * do ComboBox de operarios 4.
     */
    
    public void LoadCBTrab4(){
        jComboBoxOp4.removeAllItems(); 
        List<Operario> listaDeOperarios4=Operario.getOperarios();
        jComboBoxOp4.addItem("Selecione");
    	for(Operario operarios: listaDeOperarios4) {   	
    	jComboBoxOp4.addItem(operarios.toString());  	
        }     
    }
    /**
     * O metodo Botoes é responsável por modificar a visibilidade dos botões existentes dentro da classe quando
     * for necessário.
     * @param N Botão Novo
     * @param E Botão Editar
     * @param R Botão Excluir
     * @param S Botão Salvar
     * @param C Botão Cancelar
     */
    public void Botoes(boolean N, boolean E, boolean R, boolean S, boolean C){
        jButtonNovoT.setEnabled(N);
        jButtonEditarT.setEnabled(E);
        jButtonExcluirT.setEnabled(R);
        jButtonSalvarT.setEnabled(S);
        jButtonCancelarT.setEnabled(C); 
    }
    /**
     * Creates new form TNovoTrabalho
     */
    public TNovoTrabalho() {
        initComponents();
        jComboBoxOp1.removeAll();
        //ListaGeren=new ArrayList();
        setLocationRelativeTo(null);
        LoadTableTrab();        
        LoadCBTrab();
        LoadCBTrab2();
        LoadCBTrab3();
        LoadCBTrab4();
        Botoes(true,false,false,false,false);
        jTextFieldCodigoTrab.setEnabled(false);    
        jTextFieldNomeTrab.setEnabled(false);        
        jTextFieldCaracteristicasTrab.setEnabled(false);
        jTextFieldPeriodoTrab.setEnabled(false); 
        jComboBoxOp1.setEnabled(false);
        jComboBoxOp2.setEnabled(false);    
        jComboBoxOp3.setEnabled(false);    
        jComboBoxOp4.setEnabled(false); 
        
        //jComboBoxStatsTrab.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCaracteristicasTrab = new javax.swing.JTextField();
        jTextFieldNomeTrab = new javax.swing.JTextField();
        jTextFieldCodigoTrab = new javax.swing.JTextField();
        jLabelCodigoTrab = new javax.swing.JLabel();
        jLabelNomeTrab = new javax.swing.JLabel();
        jLabelCaracteristicasTrab = new javax.swing.JLabel();
        jLabelPeriodoTrab = new javax.swing.JLabel();
        jLabelStatusTrab = new javax.swing.JLabel();
        jLabelOp1 = new javax.swing.JLabel();
        jLabelOp2 = new javax.swing.JLabel();
        jLabelOp3 = new javax.swing.JLabel();
        jLabelOp4 = new javax.swing.JLabel();
        jComboBoxOp1 = new javax.swing.JComboBox<>();
        jButtonSalvarT = new javax.swing.JButton();
        jButtonCancelarT = new javax.swing.JButton();
        jButtonNovoT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTrab = new javax.swing.JTable();
        jComboBoxOp2 = new javax.swing.JComboBox<>();
        jComboBoxOp3 = new javax.swing.JComboBox<>();
        jComboBoxOp4 = new javax.swing.JComboBox<>();
        jComboBoxStatsTrab = new javax.swing.JComboBox<>();
        jTextFieldPeriodoTrab = new javax.swing.JTextField();
        jButtonEditarT = new javax.swing.JButton();
        jButtonFin = new javax.swing.JButton();
        jButtonExcluirT = new javax.swing.JButton();
        Fundao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Trabalho");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone-empresa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(840, 10, 210, 210);
        getContentPane().add(jTextFieldCaracteristicasTrab);
        jTextFieldCaracteristicasTrab.setBounds(170, 110, 250, 30);
        getContentPane().add(jTextFieldNomeTrab);
        jTextFieldNomeTrab.setBounds(170, 70, 250, 30);

        jTextFieldCodigoTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoTrabActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigoTrab);
        jTextFieldCodigoTrab.setBounds(170, 30, 50, 30);

        jLabelCodigoTrab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCodigoTrab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoTrab.setText("Codigo:");
        getContentPane().add(jLabelCodigoTrab);
        jLabelCodigoTrab.setBounds(110, 30, 70, 17);

        jLabelNomeTrab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomeTrab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeTrab.setText("Nome:");
        getContentPane().add(jLabelNomeTrab);
        jLabelNomeTrab.setBounds(120, 70, 70, 17);

        jLabelCaracteristicasTrab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCaracteristicasTrab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCaracteristicasTrab.setText("Característica:");
        getContentPane().add(jLabelCaracteristicasTrab);
        jLabelCaracteristicasTrab.setBounds(70, 110, 110, 20);

        jLabelPeriodoTrab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPeriodoTrab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeriodoTrab.setText("Periodo:");
        getContentPane().add(jLabelPeriodoTrab);
        jLabelPeriodoTrab.setBounds(110, 150, 70, 20);

        jLabelStatusTrab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatusTrab.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatusTrab.setText("Status:");
        getContentPane().add(jLabelStatusTrab);
        jLabelStatusTrab.setBounds(120, 190, 50, 20);

        jLabelOp1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOp1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOp1.setText("Operario 1:");
        getContentPane().add(jLabelOp1);
        jLabelOp1.setBounds(500, 30, 80, 17);

        jLabelOp2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOp2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOp2.setText("Operario 2:");
        getContentPane().add(jLabelOp2);
        jLabelOp2.setBounds(500, 70, 80, 17);

        jLabelOp3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOp3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOp3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOp3.setText("Operario 3:");
        getContentPane().add(jLabelOp3);
        jLabelOp3.setBounds(500, 120, 80, 17);

        jLabelOp4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOp4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOp4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOp4.setText("Operario 4:");
        getContentPane().add(jLabelOp4);
        jLabelOp4.setBounds(500, 160, 90, 17);

        jComboBoxOp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOp1);
        jComboBoxOp1.setBounds(590, 30, 180, 20);

        jButtonSalvarT.setText("Salvar");
        jButtonSalvarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarT);
        jButtonSalvarT.setBounds(580, 220, 80, 23);

        jButtonCancelarT.setText("Cancelar");
        jButtonCancelarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarT);
        jButtonCancelarT.setBounds(580, 260, 80, 23);

        jButtonNovoT.setText("Novo");
        jButtonNovoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoT);
        jButtonNovoT.setBounds(717, 220, 70, 23);

        jTableTrab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTrab.setToolTipText("");
        jTableTrab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTrabMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTrab);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 350, 1040, 170);

        jComboBoxOp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        getContentPane().add(jComboBoxOp2);
        jComboBoxOp2.setBounds(590, 70, 180, 20);

        jComboBoxOp3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        getContentPane().add(jComboBoxOp3);
        jComboBoxOp3.setBounds(590, 120, 180, 20);

        jComboBoxOp4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        getContentPane().add(jComboBoxOp4);
        jComboBoxOp4.setBounds(590, 160, 180, 20);

        jComboBoxStatsTrab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        jComboBoxStatsTrab.setEnabled(false);
        getContentPane().add(jComboBoxStatsTrab);
        jComboBoxStatsTrab.setBounds(170, 190, 100, 20);
        getContentPane().add(jTextFieldPeriodoTrab);
        jTextFieldPeriodoTrab.setBounds(170, 150, 250, 30);

        jButtonEditarT.setText("Editar");
        jButtonEditarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarT);
        jButtonEditarT.setBounds(720, 260, 70, 23);

        jButtonFin.setText("FinalizarTrabalho");
        jButtonFin.setEnabled(false);
        jButtonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFin);
        jButtonFin.setBounds(20, 310, 130, 20);

        jButtonExcluirT.setText("Excluir");
        jButtonExcluirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirT);
        jButtonExcluirT.setBounds(950, 310, 70, 23);

        Fundao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tumblr_static_background.jpg"))); // NOI18N
        getContentPane().add(Fundao);
        Fundao.setBounds(0, 0, 1130, 660);

        setSize(new java.awt.Dimension(1077, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jTextFieldCodigoTrabActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    } 
    /**
     * O evento do botão novo é responsável por limpar todos os campos e atribuir as visibilidades necessárias. 
     * @param evt Evento do Botao Novo
     */

    private void jButtonNovoTActionPerformed(java.awt.event.ActionEvent evt) {                                             
        flag=1;
        jTextFieldCodigoTrab.setText("");  
        jTextFieldNomeTrab.setText("");        
        jTextFieldCaracteristicasTrab.setText("");
        jTextFieldPeriodoTrab.setText("");
        jComboBoxOp1.setSelectedIndex(0);
        jComboBoxOp2.setSelectedIndex(0);
        jComboBoxOp3.setSelectedIndex(0);
        jComboBoxOp4.setSelectedIndex(0);
        jTextFieldCodigoTrab.setEnabled(false);    
        jTextFieldNomeTrab.setEnabled(true);        
        jTextFieldCaracteristicasTrab.setEnabled(true);
        jTextFieldPeriodoTrab.setEnabled(true); 
        jComboBoxOp1.setEnabled(true);
        jComboBoxOp2.setEnabled(true);    
        jComboBoxOp3.setEnabled(true);    
        jComboBoxOp4.setEnabled(true); 
        
        Botoes(false,false,false,true,true); 
    }  
    /**
     * O evento do botao cancelar é responsável por limpar todos os campos necessarios.
     * @param evt
     */

    private void jButtonCancelarTActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        jTextFieldCodigoTrab.setText("");  
        jTextFieldNomeTrab.setText("");        
        jTextFieldCaracteristicasTrab.setText("");
        jTextFieldPeriodoTrab.setText(""); 
        Botoes(true,false,false,false,false);    
    } 
    /**
     * O evento do botão salvar é responsável por instanciar novos trabalhos e salva-lós conforme as informações 
     * passadas pelo usuário ou editar trabalhos que já foram instanciados anteriormente. . Para fazer isso é
     * invocado o método SalvarTrabalgo da camada Controller.Após realizada as operações todos os campos são limpos
     * e desabilitados.
     * @param evt Evento do botão salvar
     */

    private void jButtonSalvarTActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if(flag==1){  
        if (TrabalhoControl.SalvarTrabalho(Modelo4.getRowCount(),jTextFieldNomeTrab.getText(),
                jTextFieldCaracteristicasTrab.getText(),jTextFieldPeriodoTrab.getText(), (String) jComboBoxOp1.getSelectedItem(),
                (String) jComboBoxOp2.getSelectedItem(),(String) jComboBoxOp3.getSelectedItem(),(String) jComboBoxOp4.getSelectedItem(), (String) jComboBoxStatsTrab.getSelectedItem())){              
           this.LoadTableTrab();
           JOptionPane.showMessageDialog(this, "Trabalho salvo com sucesso!");      
       }
       else
           JOptionPane.showMessageDialog(this, "Erro ao salvar aluno!");
        }else
            if(flag==2){ if (TrabalhoControl.SalvarTrabalho(Integer.parseInt(jTextFieldCodigoTrab.getText()),jTextFieldNomeTrab.getText(),
                jTextFieldCaracteristicasTrab.getText(),jTextFieldPeriodoTrab.getText(), (String) jComboBoxOp1.getSelectedItem(),
                (String) jComboBoxOp2.getSelectedItem(),(String) jComboBoxOp3.getSelectedItem(),(String) jComboBoxOp4.getSelectedItem(), (String) jComboBoxStatsTrab.getSelectedItem())){              
           this.LoadTableTrab();
           JOptionPane.showMessageDialog(this, "Trabalho salvo com sucesso!");      
       }
       else
           JOptionPane.showMessageDialog(this, "Erro ao salvar aluno!");
            }
        jTextFieldCodigoTrab.setText("");  
        jTextFieldNomeTrab.setText("");        
        jTextFieldCaracteristicasTrab.setText("");
        jTextFieldPeriodoTrab.setText("");
        jComboBoxOp1.setSelectedIndex(0);
        jComboBoxOp2.setSelectedIndex(0);
        jComboBoxOp3.setSelectedIndex(0);
        jComboBoxOp4.setSelectedIndex(0);
        jComboBoxOp1.setEnabled(false);
        jComboBoxOp2.setEnabled(false);
        jComboBoxOp3.setEnabled(false);
        jComboBoxOp4.setEnabled(false);
        jTextFieldCodigoTrab.setEnabled(false);  
        jTextFieldNomeTrab.setEnabled(false);       
        jTextFieldCaracteristicasTrab.setEnabled(false);  
        jTextFieldPeriodoTrab.setEnabled(false); 
        jComboBoxStatsTrab.setEnabled(false);
        jComboBoxStatsTrab.setSelectedIndex(0);
        jButtonFin.setEnabled(false);

        Botoes(true,false,false,false,false);
    }
    /**
     * O evento do jTableTrabMouseClicked é responsável por carregar as informações da tabela nos respectivos
     * campos.
     * @param evt evento mouse clicked da tabela
     */

    private void jTableTrabMouseClicked(java.awt.event.MouseEvent evt) {                                        
            // TODO add your handling code here:
       Botoes(true,true,true,false,false);
        jComboBoxOp1.setSelectedIndex(0);
        jComboBoxOp2.setSelectedIndex(0);
        jComboBoxOp3.setSelectedIndex(0);
        jComboBoxOp4.setSelectedIndex(0);
        index = jTableTrab.getSelectedRow();       
        if(index>=0 && index<Modelo4.getRowCount()){
            String temp[] = Modelo4.getTrabalhos(index);           
            jTextFieldCodigoTrab.setText(temp[0]); 
            jTextFieldNomeTrab.setText(temp[1]); 
            jTextFieldCaracteristicasTrab.setText(temp[2]);
            jTextFieldPeriodoTrab.setText(temp[3]);
            jComboBoxOp1.setSelectedItem(temp[4]);
            jComboBoxOp2.setSelectedItem(temp[5]);
            jComboBoxOp3.setSelectedItem(temp[6]);
            jComboBoxOp4.setSelectedItem(temp[7]);
            jComboBoxStatsTrab.setSelectedItem(temp[8]);            
    }       
        jTextFieldCodigoTrab.setEnabled(false);  
        jTextFieldNomeTrab.setEnabled(false);       
        jTextFieldCaracteristicasTrab.setEnabled(false);  
        jTextFieldPeriodoTrab.setEnabled(false);

        jComboBoxOp1.setEnabled(false);
        jComboBoxOp2.setEnabled(false);    
        jComboBoxOp3.setEnabled(false);    
        jComboBoxOp4.setEnabled(false); 
        jButtonFin.setEnabled(true);
        Botoes(true,true,true,false,false);
    }                                       

    private void jComboBoxOp1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }          
    /**
     * O evento do botão editar é responsável por atribuir as visibilidades dos campos conforme a necessidade.
     * @param evt Evento do Botao Editar
     */

    private void jButtonEditarTActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        flag=2;
        jTextFieldCodigoTrab.setEnabled(false);  
        jTextFieldNomeTrab.setEnabled(true);       
        jTextFieldCaracteristicasTrab.setEnabled(true);  
        jTextFieldPeriodoTrab.setEnabled(true);
        jComboBoxOp1.setEnabled(true);
        jComboBoxOp2.setEnabled(true);    
        jComboBoxOp3.setEnabled(true);    
        jComboBoxOp4.setEnabled(true);;
        jComboBoxStatsTrab.setEnabled(false);
        jButtonFin.setEnabled(false);
        Botoes(false,false,false,true,true);
    }   
    /**
     * O evento do botão jButtonFinActionPerformed é responsável por dar a característica de trabalho finalizado
     * a algum trabalho que já tenha sido instanciado. Para isso ele atribuí falso ao status do Trabalho.
     * @param evt Evento Botao jButtonFinActionPerformed
     */

    private void jButtonFinActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        flag=2;
        int index = jTableTrab.getSelectedRow();
        if(index>=0 && index<Modelo4.getRowCount()){
            Modelo4.setValueAt(false, index, 9);
        }
        jComboBoxStatsTrab.setSelectedIndex(1);        
        Botoes(false,false,false,true,false);
    }     
    /**
     * O evento do botão excluir é responsável por excluir algum Trabalho que já tenha sido anteriormente 
     * instanciado. Para isso ele invoca o metodo SalvarTrabalho da camada Controller. Após excluí-lo o evento
     * atualiza a tabela com a respectiva ação.
     * @param evt Evento do Botao Excluir
     */

    private void jButtonExcluirTActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        flag=3;
        
        if (TrabalhoControl.SalvarTrabalho(Modelo4.getRowCount(),jTextFieldNomeTrab.getText(),
                jTextFieldCaracteristicasTrab.getText(),jTextFieldPeriodoTrab.getText(), (String) jComboBoxOp1.getSelectedItem(),
                (String) jComboBoxOp2.getSelectedItem(),(String) jComboBoxOp3.getSelectedItem(),(String) jComboBoxOp4.getSelectedItem(), (String) jComboBoxStatsTrab.getSelectedItem())){              
           this.LoadTableTrab();
           JOptionPane.showMessageDialog(this, "Trabalho excluído com sucesso!");      
       }
        jTextFieldCodigoTrab.setText("");  
        jTextFieldNomeTrab.setText("");        
        jTextFieldCaracteristicasTrab.setText("");
        jTextFieldPeriodoTrab.setText("");
        
        Botoes(true,false,false,true,false);
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TNovoTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TNovoTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TNovoTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TNovoTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TNovoTrabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Fundao;
    private javax.swing.JButton jButtonCancelarT;
    private javax.swing.JButton jButtonEditarT;
    private javax.swing.JButton jButtonExcluirT;
    private javax.swing.JButton jButtonFin;
    private javax.swing.JButton jButtonNovoT;
    private javax.swing.JButton jButtonSalvarT;
    private javax.swing.JComboBox<String> jComboBoxOp1;
    private javax.swing.JComboBox<String> jComboBoxOp2;
    private javax.swing.JComboBox<String> jComboBoxOp3;
    private javax.swing.JComboBox<String> jComboBoxOp4;
    private javax.swing.JComboBox<String> jComboBoxStatsTrab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCaracteristicasTrab;
    private javax.swing.JLabel jLabelCodigoTrab;
    private javax.swing.JLabel jLabelNomeTrab;
    private javax.swing.JLabel jLabelOp1;
    private javax.swing.JLabel jLabelOp2;
    private javax.swing.JLabel jLabelOp3;
    private javax.swing.JLabel jLabelOp4;
    private javax.swing.JLabel jLabelPeriodoTrab;
    private javax.swing.JLabel jLabelStatusTrab;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTrab;
    private javax.swing.JTextField jTextFieldCaracteristicasTrab;
    private javax.swing.JTextField jTextFieldCodigoTrab;
    private javax.swing.JTextField jTextFieldNomeTrab;
    private javax.swing.JTextField jTextFieldPeriodoTrab;
    // End of variables declaration                   
}
